name: Terraform Manual Pipeline

on:
  workflow_dispatch:  # 🚀 Manual trigger

jobs:
  terraform:
    name: Terraform Init and Plan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.0  # ✅ Jo version tu use karta hai

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan
